name: Infinity AI

on: workflow_dispatch
jobs:
  Prompt:
    name: The Infinitys AI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: secret
        env: # Or as an environment variable
          GOOGLE_AI_STUDIO_KEY: ${{ secrets.GoogleAiStudioKey }}
      - run: python ./The-Infinitys-AI/AI.py
