name: Infinity AI

permissions:
  contents: read
  pages: write
  id-token: write

on: workflow_dispatch
jobs:
  Prompt:
    name: The Infinitys AI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install scratchattach
      - run: python ./The-Infinitys-AI/AI.py
        env: # Or as an environment variable
          GOOGLE_AI_STUDIO_KEY: ${{ secrets.GOOGLE_AI_STUDIO_KEY }}
          SCRATCH_INFINITYSERVERSYSTEM_PASSWORD: ${{ secrets.SCRATCH_INFINITYSERVERSYSTEM_PASSWORD }}
